services:
  ctfd:
    build: .
    user: ctfd
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=9
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - .:/opt/CTFd
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - ./CTFd/themes:/opt/CTFd/CTFd/themes
      - ./CTFd/plugins:/opt/CTFd/CTFd/plugins
    depends_on:
      - db
    networks:
      default:
      internal:
      ctfrei-bot:

  bot:
    build:
      context: ../CTFREI-Bot
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ../CTFREI-Bot/conf.json:/home/discordbot/conf.json:ro
      - ../CTFREI-Bot/bot_functions.py:/home/discordbot/bot_functions.py:ro
      - ../CTFREI-Bot/main.py:/home/discordbot/main.py:ro
      - ../CTFREI-Bot/registering.py:/home/discordbot/registering.py:ro
      - ../CTFREI-Bot/settings.py:/home/discordbot/settings.py:ro
      - ../CTFREI-Bot/log:/home/discordbot/log:rw
      # - type: bind
      #   source: /srv/CTFREI-Bot/loops.log
      #   target: /home/discordbot/loops.log
    networks:
      default:
      ctfrei-bot:

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
      internal:

networks:
  default:
  internal:
    internal: true
  ctfrei-bot:
    internal: true